name: "HA Dashboard Screenshot"
description: "Captures a screenshot of the Home Assistant dashboard using Puppeteer"
version: "0.0.1"
slug: "ha-dashboard-screenshot"
startup: "once"
boot: "manual"
options:
  url: "http://homeassistant.local:8123/lovelace/default_view"
schema":
  url: "str"
  token: "str"

